version: '3'

services:

  events_db:
    image: mysql:8.0
    container_name: events_db
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=events_db
      - MYSQL_HOST=events_db
    ports:
      - 3306:3306

  events-portal:
    build:
      context: ./docker
    restart: on-failure
    depends_on:
      - events_db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=events_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=events_db
      - DATABASE_PORT=3306